name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  # Disable husky
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: pnpm install

      # The following job would fail without the `--libs-and-apps` flag.
      # We currently don't auto-format this file after it has changed
      # and therefore using the flag works around that issue by limiting
      # the directories being checked to nx project directories only.
      - run: npx nx format:check --libs-and-apps

      - run: npx nx affected -t lint --parallel=3 --exclude playground
      - run: npx nx affected -t test --parallel=3 --exclude playground
      - run: npx nx affected -t build --parallel=3 --exclude playground

      - name: Validate most recent commit with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: >
          npx commitlint
          --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}
          --to ${{ github.event.pull_request.head.sha }}
          --verbose
